export const data = [
  {
    title: "Land of 1,000,000 Years Ago",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "test",
    year: 1959,
  },
  {
    title: "Thirty-One of the classics",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "test",
    year: 1959,
  },
  {
    title: "Jumper",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testDave's Rag (1959)",
    year: 1959,
  },
  {
    title: "Rush Call",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testDave's Rag (1960)",
    year: 1960,
  },
  {
    title: "The Cursed Expedition",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "I've Got to Get Away!",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "Hotel at the End of the Road",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "Never Look Behind You",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "The Other Side of the Fog",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "The Stranger",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "The Thing at the Bottom of the Well",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPeople, Places and Things (1960)",
    year: 1960,
  },
  {
    title: "The Pit and the Pendulum",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe Pit and the Pendulum (1961)",
    year: 1961,
  },
  {
    title: "The Undead",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe Undead (1963)",
    year: 1963,
  },
  {
    title: "Trigger Finger",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testTrigger Finger (1963)",
    year: 1963,
  },
  {
    title: "The Star Invaders",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Star Invaders (1964)",
    year: 1964,
  },
  {
    title: "Codename: Mousetrap",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Drum (October 27, 1965)",
    year: 1965,
  },
  {
    title: "I Was a Teenage Grave Robber",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testComics Review (1965)",
    year: 1965,
  },
  {
    title: "The 43rd Dream",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Drum (January 29, 1966)",
    year: 1966,
  },
  {
    title: "The Glass Floor",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testStartling Mystery Stories (Fall 1967)",
    year: 1967,
  },
  {
    title: "Cain Rose Up",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testUbris (Spring 1968)",
    year: 1968,
  },
  {
    title: "Here There Be Tygers",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testUbris (Spring 1968)",
    year: 1968,
  },
  {
    title: "Harrison State Park '68",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testUbris (Fall 1968)",
    year: 1968,
  },
  {
    title: "Strawberry Spring",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testUbris (Fall 1968)",
    year: 1968,
  },
  {
    title: "Night Surf",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testUbris (Spring 1969)",
    year: 1969,
  },
  {
    title: "The Reaper's Image",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testStartling Mystery Stories (Spring 1969)",
    year: 1969,
  },
  {
    title: "The Dark Man",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testUbris (Fall 1969)",
    year: 1969,
  },
  {
    title: "Stud City",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testUbris (Fall 1969)",
    year: 1969,
  },
  {
    title: "Slade",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Maine Campus (June 11 – August 6, 1970)",
    year: 1970,
  },
  {
    title: "Graveyard Shift",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (October 1970)",
    year: 1970,
  },
  {
    title: "Donovan's Brain",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testMoth  (1970)",
    year: 1970,
  },
  {
    title: "Silence",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testMoth  (1970)",
    year: 1970,
  },
  {
    title: "The Blue Air Compressor",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testOnan (January 1971)",
    year: 1971,
  },
  {
    title: "In the Key Chords of Dawn",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testOnan (January 1971)",
    year: 1971,
  },
  {
    title: "I Am the Doorway",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (March 1971)",
    year: 1971,
  },
  {
    title: "Brooklyn August",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testIo #10 (1971)",
    year: 1971,
  },
  {
    title: "She Has Gone to Sleep While...",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testContraband #1 (1971)",
    year: 1971,
  },
  {
    title: "Woman with Child",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testContraband #1 (1971)",
    year: 1971,
  },
  {
    title: "The Hardcase Speaks",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testContraband #2 (1971)",
    year: 1971,
  },
  {
    title: "Suffer the Little Children",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (February 1972)",
    year: 1972,
  },
  {
    title: "The Fifth Quarter",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (April 1972)",
    year: 1972,
  },
  {
    title: "Battleground",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (September 1972)",
    year: 1972,
  },
  {
    title: "The Mangler",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (December 1972)",
    year: 1972,
  },
  {
    title: "The Boogeyman",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (March 1973)",
    year: 1973,
  },
  {
    title: "Trucks",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (June 1973)",
    year: 1973,
  },
  {
    title: "Gray Matter",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (October 1973)",
    year: 1973,
  },
  {
    title: "It Grows on You",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMarshroots (Fall 1973)",
    year: 1973,
  },
  {
    title: "Sometimes They Come Back",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (March 1974)",
    year: 1974,
  },
  {
    title: "The Lawnmower Man",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (May 1975)",
    year: 1975,
  },
  {
    title: "The Revenge of Lard Ass Hogan",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Maine Review (July 1975)",
    year: 1975,
  },
  {
    title: "Weeds",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (May 1976)",
    year: 1976,
  },
  {
    title: "The Ledge",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testPenthouse (July 1976)",
    year: 1976,
  },
  {
    title: "I Know What You Need",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCosmopolitan (September 1976)",
    year: 1976,
  },
  {
    title: "Children of the Corn",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testPenthouse (March 1977)",
    year: 1977,
  },
  {
    title: "One for the Road",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMaine (March/April 1977)",
    year: 1977,
  },
  {
    title: "The Cat from Hell",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (June 1977)",
    year: 1977,
  },
  {
    title: "The King Family and the Wicked Witch",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testFlint (August 25, 1977)",
    year: 1977,
  },
  {
    title: "The Man Who Loved Flowers",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testGallery (August 1977)",
    year: 1977,
  },
  {
    title: "Jerusalem's Lot",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Shift (February 1978)",
    year: 1978,
  },
  {
    title: "The Last Rung on the Ladder",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Shift (February 1978)",
    year: 1978,
  },
  {
    title: "Quitters, Inc.",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Shift (February 1978)",
    year: 1978,
  },
  {
    title: "The Woman in the Room",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Shift (February 1978)",
    year: 1978,
  },
  {
    title: "The Night of the Tiger",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (February 1978)",
    year: 1978,
  },
  {
    title: "Nona",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testShadows (September 1978)",
    year: 1978,
  },
  {
    title: "The Gunslinger",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (October 1978)",
    year: 1978,
  },
  {
    title: "Man With a Belly",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCavalier (December 1978)",
    year: 1978,
  },
  {
    title: "The Crate",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testGallery (July 1979)",
    year: 1979,
  },
  {
    title: "The Mist",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testDark Forces (January 1, 1980)",
    year: 1980,
  },
  {
    title: "Crouch End",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNew Tales of the Cthulhu Mythos (January 1980)",
    year: 1980,
  },
  {
    title: "The Way Station",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (April 1980)",
    year: 1980,
  },
  {
    title: "Big Wheels: A Tale of the Laundry Game (Milkman #2)",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNew Terrors (July 1980)",
    year: 1980,
  },
  {
    title: "The Monkey",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testGallery (November 1980)",
    year: 1980,
  },
  {
    title: "The Wedding Gig",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testEllery Queen's Mystery Magazine (December 1980)",
    year: 1980,
  },
  {
    title: "The Oracle and the Mountains",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (February 1981)",
    year: 1981,
  },
  {
    title: "The Jaunt",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Twilight Zone Magazine (June 1981)",
    year: 1981,
  },
  {
    title: "The Slow Mutants",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (July 1981)",
    year: 1981,
  },
  {
    title: "The Man Who Would Not Shake Hands",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testShadows 4 (October 1981)",
    year: 1981,
  },
  {
    title: "The Monster in the Closet",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testLadies' Home Journal (October 1981)",
    year: 1981,
  },
  {
    title: "The Bird and the Album",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testA Fantasy Reader (October 30, 1981)",
    year: 1981,
  },
  {
    title: "The Gunslinger and the Dark Man",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (November 1981)",
    year: 1981,
  },
  {
    title: "The Reach",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testYankee (November 1981)",
    year: 1981,
  },
  {
    title: "Survivor Type",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testTerrors (July 1982)",
    year: 1982,
  },
  {
    title: "Before the Play",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testWhispers (August 1982)",
    year: 1982,
  },
  {
    title: "Apt Pupil",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testDifferent Seasons (August 27, 1982)",
    year: 1982,
  },
  {
    title: "The Body",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testDifferent Seasons (August 27, 1982)",
    year: 1982,
  },
  {
    title: "The Breathing Method",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testDifferent Seasons (August 27, 1982)",
    year: 1982,
  },
  {
    title: "Rita Hayworth and Shawshank Redemption",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testDifferent Seasons (August 27, 1982)",
    year: 1982,
  },
  {
    title: "The Raft",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testGallery (November 1982)",
    year: 1982,
  },
  {
    title: "Skybar",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Do-It-Yourself Bestseller (1982)",
    year: 1982,
  },
  {
    title: "Word Processor of the Gods",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testPlayboy (January 1983)",
    year: 1983,
  },
  {
    title: "Uncle Otto's Truck",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testYankee (October 1983)",
    year: 1983,
  },
  {
    title: "Cycle of the Werewolf",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testLand of Enchantment (November 1983)",
    year: 1983,
  },
  {
    title: "The Return of Timmy Baterman",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testSatyricon II (1983)",
    year: 1983,
  },
  {
    title: "Gramma",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testWeirdbook (Spring 1984)",
    year: 1984,
  },
  {
    title: "Mrs. Todd's Shortcut",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testRedbook (May 1984)",
    year: 1984,
  },
  {
    title: "The Ballad of the Flexible Bullet",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (June 1984)",
    year: 1984,
  },
  {
    title: "The Revelations of 'Becka Paulson",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testRolling Stone (July 19 – August 2, 1984)",
    year: 1984,
  },
  {
    title: "Beachworld",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testWeird Tales (Fall 1984)",
    year: 1984,
  },
  {
    title: "Dolan's Cadillac",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testCastle Rock (February – June 1985)",
    year: 1985,
  },
  {
    title: "For Owen",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testSkeleton Crew (June 1985)",
    year: 1985,
  },
  {
    title: "Morning Deliveries (Milkman #1)",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testSkeleton Crew (June 1985)",
    year: 1985,
  },
  {
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testSkeleton Crew (June 1985)",
    year: 1985,
  },
  {
    title: "For the Birds",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testBred Any Good Rooks Lately? (January 1986)",
    year: 1986,
  },
  {
    title: "The End of the Whole Mess",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testOmni (October 1986)",
    year: 1986,
  },
  {
    title: "Popsy",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMasques II (June 1987)",
    year: 1987,
  },
  {
    title: "The Doctor's Case",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Adventures of Sherlock Holmes (November 1987)",
    year: 1987,
  },
  {
    title: "The Night Flier",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testPrime Evil (June 1988)",
    year: 1988,
  },
  {
    title: "Dedication",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Visions 5 (August 1988)",
    year: 1988,
  },
  {
    title: "The Reploids",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Visions 5 (August 1988)",
    year: 1988,
  },
  {
    title: "Sneakers",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNight Visions 5 (August 1988)",
    year: 1988,
  },
  {
    title: "Rainy Season",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMidnight Graffiti (Spring 1989)",
    year: 1989,
  },
  {
    title: "Home Delivery",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testBook of the Dead (June 1989)",
    year: 1989,
  },
  {
    title: "My Pretty Pony",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMy Pretty Pony (September 1989)",
    year: 1989,
  },
  {
    title: "An Evening at God's",
    category: "O5xlgPJzjKiMPjojNkFq",
    Publisher: "testInstitute for Advanced Theater Training (April 23, 1990)",
    year: 1990,
  },
  {
    title: "The Langoliers",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testFour Past Midnight (September 1990)",
    year: 1990,
  },
  {
    title: "The Library Policeman",
    category: "9RP5ptFI0K4XgqDMZ27Z",
    Publisher: "testFour Past Midnight (September 1990)",
    year: 1990,
  },
  {
    title: "Secret Window, Secret Garden",
    category: "History",
    Publisher: "testFour Past Midnight (September 1990)",
    year: 1990,
  },
  {
    title: "The Sun Dog",
    category: "History",
    Publisher: "testFour Past Midnight (September 1990)",
    year: 1990,
  },
  {
    title: "The Bear",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (December 1990)",
    year: 1990,
  },
  {
    title: "The Moving Finger",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (December 1990)",
    year: 1990,
  },
  {
    title: "You Know They Got a Hell of a Band",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testShock Rock (January 1992)",
    year: 1992,
  },
  {
    title: "Chattery Teeth",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testCemetery Dance (Fall 1992)",
    year: 1992,
  },
  {
    title: "The Beggar and the Diamond",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNightmares & Dreamscapes (September 1993)",
    year: 1993,
  },
  {
    title: "The House on Maple Street",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNightmares & Dreamscapes (September 1993)",
    year: 1993,
  },
  {
    title: "Sorry, Right Number",
    category: "7vsVcVrtnENrpuXpRJfv",
    Publisher: "testNightmares & Dreamscapes (September 1993)",
    year: 1993,
  },
  {
    title: "The Ten O'Clock People",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNightmares & Dreamscapes (September 1993)",
    year: 1993,
  },
  {
    title: "Umney's Last Case",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNightmares & Dreamscapes (September 1993)",
    year: 1993,
  },
  {
    title: "Jhonathan and the Witches",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testFirst Words (October 1993)",
    year: 1993,
  },
  {
    title: "The Killer",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testFamous Monsters of Filmland #202 (Spring 1994)",
    year: 1994,
  },
  {
    title: "Blind Willie",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testAntaeus #75/76 (October 1994)",
    year: 1994,
  },
  {
    title: "The Man in the Black Suit",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Yorker (October 31, 1994)",
    year: 1994,
  },
  {
    title: "Dino",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testSalt Hill Journal (Fall 1994)",
    year: 1994,
  },
  {
    title: "Luckey Quarter",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testUSA Weekend (June 30 – July 2, 1995)",
    year: 1995,
  },
  {
    title: "The Bone Church",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testPlayboy (November 2009)",
    year: 2009,
  },
  {
    title: "Lunch at the Gotham Café",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testDark Love (November 1995)",
    year: 1995,
  },
  {
    title: "Autopsy Room Four",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testSix Stories (April 1997)",
    year: 1997,
  },
  {
    title: "L. T.'s Theory of Pets",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testSix Stories (April 1997)",
    year: 1997,
  },
  {
    title: "General",
    category: "YVNG3xH6mUdpiPAvVBO0",
    Publisher: "testScreamplays  (September 1997)",
    year: 1997,
  },
  {
    title: "Everything's Eventual",
    category: "History",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (October–November 1997)",
    year: 1997,
  },
  {
    title: "That Feeling, You Can Only Say What It Is in French",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Yorker (June 22, 1998)",
    year: 1998,
  },
  {
    title: "The Little Sisters of Eluria",
    category: "History",
    Publisher: "testLegends (October 1998)",
    year: 1998,
  },
  {
    title: "The New Lieutenant's Rap",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Lieutenant's Rap (April 1999)",
    year: 1999,
  },
  {
    title: "The Road Virus Heads North",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "test999 (September 7, 1999)",
    year: 1999,
  },
  {
    title: "Hearts in Atlantis",
    category: "History",
    Publisher: "testHearts in Atlantis (September 14, 1999)",
    year: 1999,
  },
  {
    title: "Heavenly Shades of Night Are Falling",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testHearts in Atlantis (September 14, 1999)",
    year: 1999,
  },
  {
    title: "Low Men in Yellow Coats",
    category: "History",
    Publisher: "testHearts in Atlantis (September 14, 1999)",
    year: 1999,
  },
  {
    title: "Why We're in Vietnam",
    category: "History",
    Publisher: "testHearts in Atlantis (September 14, 1999)",
    year: 1999,
  },
  {
    title: "1408",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testBlood and Smoke (November 1999)",
    year: 1999,
  },
  {
    title: "In the Deathroom",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testBlood and Smoke (November 1999)",
    year: 1999,
  },
  {
    title: "Riding the Bullet",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testRiding the Bullet (March 14, 2000)",
    year: 2000,
  },
  {
    title: "The Old Dude's Ticker",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testNECON XX (July 2000)",
    year: 2000,
  },
  {
    title: "All That You Love Will Be Carried Away",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Yorker (January 29, 2001)",
    year: 2001,
  },
  {
    title: "Calla Bryn Sturgis",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "teststephenking.com (2001)",
    year: 2001,
  },
  {
    title: "The Death of Jack Hamilton",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Yorker (December 24–31, 2001)",
    year: 2001,
  },
  {
    title: "The Tale of Gray Dick",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMcSweeney's Mammoth Treasury of Thrilling Tales (March 25, 2003)",
    year: 2003,
  },
  {
    title: "Harvey's Dream",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testThe New Yorker (June 30, 2003)",
    year: 2003,
  },
  {
    title: "Stationary Bike",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testBorderlands 5 (November 2003)",
    year: 2003,
  },
  {
    title: "Rest Stop",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testEsquire (December 2003)",
    year: 2003,
  },
  {
    title: "Lisey and the Madman",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testMcSweeney’s Enchanted Chamber of Astonishing Stories (2004)",
    year: 2004,
  },
  {
    title: "The Furnace",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testWeekly Reader (September 2005)",
    year: 2005,
  },
  {
    title: "The Things They Left Behind",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testTransgressions  (May 2005)",
    year: 2005,
  },
  {
    title: "Memory",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testTin House #28 (July 2006)",
    year: 2006,
  },
  {
    title: "Willa",
    category: "iRrCyog1QZ9XoXWdiRl7",
    Publisher: "testPlayboy (December 2006)",
    year: 2006,
  },
  {
    title: "Graduation Afternoon",
    category: "XFkeIDY5m4LAXmFm6Qde",
    Publisher: "testPostscripts (March 2007)",
    year: 2007,
  },
  {
    title: "The Gingerbread Girl",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testEsquire (July 2007)",
    year: 2007,
  },
  {
    title: "Ayana",
    category: "XFkeIDY5m4LAXmFm6Qde",
    Publisher: "testThe Paris Review (Fall 2007)",
    year: 2007,
  },
  {
    title: "Mute",
    category: "XFkeIDY5m4LAXmFm6Qde",
    Publisher: "testPlayboy (December 2007)",
    year: 2007,
  },
  {
    title: "A Very Tight Place",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testMcSweeney's #27 (Spring 2008)",
    year: 2008,
  },
  {
    title: "The New York Times at Special Bargain Rates",
    category: "XFkeIDY5m4LAXmFm6Qde",
    Publisher: "testThe Magazine of Fantasy & Science Fiction (October/November 2008)",
    year: 2008,
  },
  {
    title: "N.",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testJust After Sunset (November 2008)",
    year: 2008,
  },
  {
    title: "Throttle",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testHe Is Legend (February 1, 2009)",
    year: 2009,
  },
  {
    title: "Ur",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testUr (February 12, 2009)",
    year: 2009,
  },
  {
    title: "Morality",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testEsquire (July 2009)",
    year: 2009,
  },
  {
    title: "Mostly Old Men",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testTin House #40 (August 2009)",
    year: 2009,
  },
  {
    title: "Premium Harmony",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe New Yorker (November 9, 2009)",
    year: 2009,
  },
  {
    title: "Tommy",
    category: "8J7QFTgGBoixeNJfcBAl",
    Publisher: "testPlayboy (March 2010)",
    year: 2010,
  },
  {
    title: "Blockade Billy",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testBlockade Billy (April 2010)",
    year: 2010,
  },
  {
    title: "1922",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testFull Dark, No Stars (November 2010)",
    year: 2010,
  },
  {
    title: "Big Driver",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testFull Dark, No Stars (November 2010)",
    year: 2010,
  },
  {
    title: "Fair Extension",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testFull Dark, No Stars (November 2010)",
    year: 2010,
  },
  {
    title: "A Good Marriage",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testFull Dark, No Stars (November 2010)",
    year: 2010,
  },
  {
    title: "Herman Wouk Is Still Alive",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe Atlantic (May 2011)",
    year: 2011,
  },
  {
    title: "Under the Weather",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPaperback edition of Full Dark, No Stars (May 2011)",
    year: 2011,
  },
  {
    title: "Mile 81",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testMile 81 (September 1, 2011)",
    year: 2011,
  },
  {
    title: "The Little Green God of Agony",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testA Book of horrors (September 29, 2011)",
    year: 2011,
  },
  {
    title: "The Dune",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testGranta #117 (Fall 2011)",
    year: 2011,
  },
  {
    title: "In the Tall Grass",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testEsquire (June/July–August 2012)",
    year: 2012,
  },
  {
    title: "A Face in the Crowd",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testA Face in the Crowd (August 21, 2012)",
    year: 2012,
  },
  {
    title: "Batman and Robin Have an Altercation",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testHarper's Magazine (September 2012)",
    year: 2012,
  },
  {
    title: "Afterlife",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testTin House #56 (June 2013)",
    year: 2013,
  },
  {
    title: "The Rock and Roll Dead Zone",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testHard Listening (June 18, 2013)",
    year: 2013,
  },
  {
    title: "Summer Thunder",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testTurn Down the Lights (December 2013)",
    year: 2013,
  },
  {
    title: "Bad Little Kid",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testBad Little Kid (March 14, 2014)",
    year: 2014,
  },
  {
    title: "That Bus Is Another World",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testEsquire (August 2014)",
    year: 2014,
  },
  {
    title: "A Death",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe New Yorker (March 9, 2015)",
    year: 2015,
  },
  {
    title: "Drunken Fireworks",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testDrunken Fireworks (June 30, 2015)",
    year: 2015,
  },
  {
    title: "Mister Yummy",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe Bazaar of Bad Dreams (November 2015)",
    year: 2015,
  },
  {
    title: "Obits",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testThe Bazaar of Bad Dreams (November 2015)",
    year: 2015,
  },
  {
    title: "Cookie Jar",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testVirginia Quarterly Review (Spring 2016)",
    year: 2016,
  },
  {
    title: "The Music Room",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testPlayboy (December 2016)",
    year: 2016,
  },
  {
    title: "Gwendy's Button Box",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testGwendy's Button Box (May 2017)",
    year: 2017,
  },
  {
    title: "Thin Scenery",
    category: "O5xlgPJzjKiMPjojNkFq",
    Publisher: "testPloughshares (Summer 2017)",
    year: 2017,
  },
  {
    title: "Laurie",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "teststephenking.com (May 17, 2018)",
    year: 2018,
  },
  {
    title: "Elevation",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testElevation (October 2018)",
    year: 2018,
  },
  {
    title: "The Turbulence Expert",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testFlight or Fright (September 4, 2018)",
    year: 2018,
  },
  {
    title: "Squad D",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testShivers VIII  (April 18, 2019)",
    year: 2019,
  },
  {
    title: "The Fifth Step",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testHarper's Magazine (March 2020)",
    year: 2020,
  },
  {
    title: "If It Bleeds",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testIf It Bleeds (April 2020)",
    year: 2020,
  },
  {
    title: "The Life of Chuck",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testIf It Bleeds (April 2020)",
    year: 2020,
  },
  {
    title: "Mr. Harrigan's Phone",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testIf It Bleeds (April 2020)",
    year: 2020,
  },
  {
    title: "Rat",
    category: "yhscse0d37JkLlrw1hEp",
    Publisher: "testIf It Bleeds (April 2020)",
    year: 2020,
  },
  {
    title: "On Slide Inn Road",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testEsquire Magazine (October/November 2020)",
    year: 2020,
  },
  {
    title: "Willie the Weirdo",
    category: "3cCFfMIIZZLKzQXiELJb",
    Publisher: "testMcSweeney's 65 (September 2021)",
    year: 2021,
  }
]

export const categories = [
  {
    value: 'fantasy',
  },
  {
    value: "9RP5ptFI0K4XgqDMZ27Z",
  },
  {
    value: "iRrCyog1QZ9XoXWdiRl7",
  },
  {
    value: "8J7QFTgGBoixeNJfcBAl",
  },
  {
    value: "O5xlgPJzjKiMPjojNkFq",
  },
  {
    value: "7vsVcVrtnENrpuXpRJfv",
  },
  {
    value: "YVNG3xH6mUdpiPAvVBO0",
  },
  {
    value: "yhscse0d37JkLlrw1hEp",
  },
  {
    value: "XFkeIDY5m4LAXmFm6Qde",
  },
];